import Head from 'next/head'


import  Index from './register/index'


export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
        
    < Index />
      </main>
     
    </div>
  )
}
